parallel: gameoflife_parallel.cpp
	 g++ -Wall -g -o gameoflife_parallel gameoflife_parallel.cpp 

sequential: gameoflife_sequential.cpp
	 g++ -Wall -g -o gameoflife_sequential gameoflife_sequential.cpp 